### ISSUE TITLE
[TODO] Copy and paste clips

### ISSUE THREAD

**Issue by namse** [NamseEnt/namseent#29] opened 2021-11-21 14:36 UTC
![image](https://user-images.githubusercontent.com/3580430/142765530-724afe9c-9894-47ee-bfa5-196f1fbe2138.png)
(Larry Tesler, The copy and paste inventor)

# What result I am expecting
- Clip selection state
  - Clip editor also has selection state, like InputText focus state. You should think deeeeeply about it.
    - Scenario 1
      - Click clip
      - Ctrl C & V
      - Clip copied
    - Scenario 2
      - Click clip
      - Click TextInput or focus something inside of clip editor.
      - Ctrl C & V
      - Clip not copied because I am copying the text of TextInput
- Ctrl C & V key input handler
- Copying Policy
  - Content should be copied, but not id.
  - When the clip was copied, the location copied clip coming out is the next of playhead.

**Comment by bigfoodK** [comment] 2021-11-23 07:41
Is this a duplicate of #14?

**Comment by namse** [comment] 2021-11-25 05:52
OH YAH

**Closed** 2021-11-25 05:52 UTC
Labels: luda editor
